import { KPIMetric, SalesDataPoint, Product, Transaction } from '../types/dashboard.types';

export const mockKPIMetrics: KPIMetric[] = [
  {
    id: 'total-sales',
    label: 'Total Sales',
    value: '$127,548',
    change: 12.5,
    changeType: 'positive',
  },
  {
    id: 'active-users',
    label: 'Active Users',
    value: '8,234',
    change: -3.2,
    changeType: 'negative',
  },
  {
    id: 'alerts',
    label: 'Alerts',
    value: 23,
    changeType: 'neutral',
  },
  {
    id: 'revenue',
    label: 'Revenue',
    value: '$89,420',
    change: 8.7,
    changeType: 'positive',
  },
];

export const mockSalesData: SalesDataPoint[] = [
  { time: '00:00', sales: 12000, orders: 45 },
  { time: '02:00', sales: 15000, orders: 52 },
  { time: '04:00', sales: 13000, orders: 48 },
  { time: '06:00', sales: 18000, orders: 65 },
  { time: '08:00', sales: 25000, orders: 89 },
  { time: '10:00', sales: 32000, orders: 112 },
  { time: '12:00', sales: 38000, orders: 134 },
  { time: '14:00', sales: 35000, orders: 125 },
  { time: '16:00', sales: 41000, orders: 145 },
  { time: '18:00', sales: 45000, orders: 158 },
  { time: '20:00', sales: 39000, orders: 138 },
  { time: '22:00', sales: 28000, orders: 98 },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Premium Wireless Headphones',
    category: 'Electronics',
    sales: 1234,
    revenue: 123400,
    stock: 45,
    stockStatus: 'medium',
    trend: 'up',
  },
  {
    id: 'p2',
    name: 'Smart Watch Series 5',
    category: 'Electronics',
    sales: 987,
    revenue: 296100,
    stock: 12,
    stockStatus: 'low',
    trend: 'up',
  },
  {
    id: 'p3',
    name: 'Ergonomic Office Chair',
    category: 'Furniture',
    sales: 654,
    revenue: 130800,
    stock: 89,
    stockStatus: 'healthy',
    trend: 'stable',
  },
  {
    id: 'p4',
    name: 'Professional Camera Kit',
    category: 'Electronics',
    sales: 432,
    revenue: 345600,
    stock: 23,
    stockStatus: 'medium',
    trend: 'down',
  },
  {
    id: 'p5',
    name: 'Standing Desk Pro',
    category: 'Furniture',
    sales: 389,
    revenue: 155600,
    stock: 156,
    stockStatus: 'healthy',
    trend: 'up',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 't1',
    customerName: 'John Smith',
    productName: 'Premium Wireless Headphones',
    amount: 299.99,
    status: 'completed',
    riskLevel: 'low',
    timestamp: '2024-01-18T10:30:00',
    paymentMethod: 'Credit Card',
  },
  {
    id: 't2',
    customerName: 'Sarah Johnson',
    productName: 'Smart Watch Series 5',
    amount: 599.99,
    status: 'pending',
    riskLevel: 'medium',
    timestamp: '2024-01-18T10:25:00',
    paymentMethod: 'PayPal',
  },
  {
    id: 't3',
    customerName: 'Mike Williams',
    productName: 'Ergonomic Office Chair',
    amount: 399.99,
    status: 'completed',
    riskLevel: 'low',
    timestamp: '2024-01-18T10:20:00',
    paymentMethod: 'Credit Card',
  },
  {
    id: 't4',
    customerName: 'Emily Brown',
    productName: 'Professional Camera Kit',
    amount: 1299.99,
    status: 'failed',
    riskLevel: 'high',
    timestamp: '2024-01-18T10:15:00',
    paymentMethod: 'Debit Card',
  },
  {
    id: 't5',
    customerName: 'David Lee',
    productName: 'Standing Desk Pro',
    amount: 699.99,
    status: 'completed',
    riskLevel: 'low',
    timestamp: '2024-01-18T10:10:00',
    paymentMethod: 'Apple Pay',
  },
  {
    id: 't6',
    customerName: 'Lisa Anderson',
    productName: 'Premium Wireless Headphones',
    amount: 299.99,
    status: 'pending',
    riskLevel: 'medium',
    timestamp: '2024-01-18T10:05:00',
    paymentMethod: 'PayPal',
  },
];
